namespace: azribi

replicaCount: 3

image:
  webnodb: "wahybs/my-flask-app-ch1:v2"
  webdb: "wahybs/flask-server-app-ch3:v2"
  mongodb: "mongo:latest"

ports:
  webnodb: 5000
  webdb: 5000
  mongodb: 27017

hostnames:
  ingressHost: net4255.luxbulb.org
  webnodb: webnodb
  webdb: webdb

resources:
  requests:
    cpu: "0.1"
    memory: "100Mi"
  limits:
    cpu: "0.2"
    memory: "200Mi"

mongodb:
  username: admin
  password: admin
  dbName: flask_app_db
  collectionName: requests
  storage: "300Mi"