apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-pods-to-mongodb
  namespace: azribi
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webdb
    ports:
    - protocol: TCP
      port: 27017
