# Installer la version latest de python
FROM python:latest

# Configurer le repertoire 
WORKDIR /app

# Copier le fichier app.py dans le repertoire 
COPY app.py /app

# Installer Flask
RUN pip install flask

# Expose the port the app runs on
EXPOSE 5000


# Command to run the application
CMD ["python", "app.py"]
